version: '3'

services:
  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: companydb
      MYSQL_USER: root
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
